#! /bin/bash
# this file is executed by ssh on each connection
# https://gist.github.com/martijnvermaat/8070533

# help screen work with ssh-agent forwarding
# preserve old sockect if it exists
if [ ! -r ~/.ssh/ssh_auth_sock ] && test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# fix X11 forwarding too
# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY |
             cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
